# Generated by Django 4.0.4 on 2022-07-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='tags',
            field=models.ManyToManyField(to='main_app.tag'),
        ),
    ]
